### ISSUE TITLE
Error on Google Colab demo

### ISSUE THREAD

**Issue by daniel-dona** [Edresson/YourTTS#15]
In this demo:
https://colab.research.google.com/drive/1ftI0x16iqKgiQFgTjTDgRpOM1wC1U-yS?usp=sharing#scrollTo=vqUWMEZc2Biz

This step is failing:

```python
for sample in reference_files:
    !ffmpeg-normalize $sample -nt rms -t=-27 -o $sample -ar 16000 -f
```

```
Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg-normalize", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/__main__.py", line 544, in main
    ffmpeg_normalize.run_normalization()
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 195, in run_normalization
    raise e
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 184, in run_normalization
    media_file.run_normalization()
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_media_file.py", line 154, in run_normalization
    self._first_pass()
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_media_file.py", line 183, in _first_pass
    for _ in fun():
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_streams.py", line 155, in parse_astats
    for progress in cmd_runner.run_ffmpeg_command():
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_normalize/_cmd_utils.py", line 66, in run_ffmpeg_command
    for progress in ff.run_command_with_progress():
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_progress_yield/ffmpeg_progress_yield.py", line 108, in run_command_with_progress
    "Error running command {}: {}".format(self.cmd, str("\n".join(stderr)))
RuntimeError: Error running command ['/usr/bin/ffmpeg', '-nostdin', '-y', '-i', 'c0ac3f15-9b67-4c4c-99b5-2ea9ecdc6caf_tmp.wav', '-filter_complex', '[0:0]astats=measure_overall=Peak_level+RMS_level:measure_perchannel=0', '-vn', '-sn', '-f', 'null', '/dev/null']: ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'c0ac3f15-9b67-4c4c-99b5-2ea9ecdc6caf_tmp.wav':
Duration: 00:00:05.49, bitrate: 705 kb/s
Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s
[Parsed_astats_0 @ 0x563fda8ef540] Option 'measure_overall' not found
[AVFilterGraph @ 0x563fda8b8be0] Error initializing filter 'astats' with args 'measure_overall=Peak_level+RMS_level:measure_perchannel=0'
Error initializing complex filters.
Option not found
```

**Comment by Edresson** [comment]
Hi, 

Google collabs demos are hard to keep updated. It is an issue related to the version of ffmpeg-normalize. Install the ffmpeg-normalize==1.21.0 and the issue will be solved. I updated the collab demos to solve this problem.

I added instructions on how to use [:frog: TTS](https://github.com/coqui-ai/TTS) released model [here](https://github.com/Edresson/YourTTS#coqui-tts-released-model). Using :frog: TTS you will have the latest model without bugs.

Install the :frog:  TTS using the command: `pip install tts` and following the [instructions](https://github.com/Edresson/YourTTS#coqui-tts-released-model) :).
